# USI engine build (does NOT modify the original src/makefile)
# Usage (MSYS2 MINGW64):
#   cd src
#   mingw32-make -f Makefile.usi usi
#
# If you want to build nshogi automatically first:
#   mingw32-make -f Makefile.usi nshogi usi

CXX ?= g++
NSHOGI_BUILD ?= release

NSHOGI_OBJDIR := nshogi/build/$(NSHOGI_BUILD)_$(CXX)

# Keep flags close to the existing src/makefile defaults.
CXXFLAGS ?= -std=c++2b -I./nshogi/src -mtune=native -march=native -O3
#CXXFLAGS ?= -std=c++2b -I./nshogi/src -mtune=native -march=native -O3 -g -fno-omit-frame-pointer
#CXXFLAGS ?= -std=c++2b -I./nshogi/src -mtune=native -march=native -O0 -g -pg -fno-omit-frame-pointer

LDFLAGS ?= -L./$(NSHOGI_OBJDIR)/lib -lnshogi_static
#LDFLAGS  += -pg

USI_TARGET ?= debug.exe
USI_SRCS := \
	engine/usi.cpp \
	engine/search.cpp \
	engine/StatewithNNUE.cpp \
	engine/nn/nnue_nn.cpp \
	model/weights.cpp

.PHONY: usi nshogi clean

usi:
	$(CXX) $(CXXFLAGS) $(USI_SRCS) -o $(USI_TARGET) $(LDFLAGS)

nshogi:
	$(MAKE) -C nshogi libnshogi BUILD=$(NSHOGI_BUILD) AVX2=1 CXX=$(CXX)

clean:
	rm -f $(USI_TARGET) $(USI_SRCS:.cpp=.o)